/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CartIcon: React.FC = () => (
  <div className="flex items-start self-start">
    <div className="flex items-start pr-1.5 pb-px mt-2">
      <div className="flex items-start w-[21px]">
        <div className="flex items-start w-[21px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e1632fd1afd0c84e0350e3aac6369b7c3ec49fdbcfac9f409f041b70d8230bc3?placeholderIfAbsent=true&apiKey=ae55c71ab31c4b56a85baaeb8b56efa9"
            className="object-contain aspect-square w-[21px]"
            alt="Shopping cart"
          />
        </div>
      </div>
    </div>
    <div className="px-1 pt-px pb-0.5 text-xs text-center text-white whitespace-nowrap bg-red-400 rounded-2xl">
      0
    </div>
  </div>
);

export default CartIcon;
