/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CurrencySelector: React.FC = () => (
  <div className="flex relative flex-col justify-center self-stretch py-0.5 text-base leading-10 text-white whitespace-nowrap aspect-[1.256] min-h-[44px] w-[54px]">
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/09289c25b3b785ec69a03990ef48ef28425ea2ccdd93a1de74ac05c14e0728f7?placeholderIfAbsent=true&apiKey=ae55c71ab31c4b56a85baaeb8b56efa9"
      className="object-cover absolute inset-0 size-full"
      alt=""
    />
    <div className="overflow-hidden relative w-full">USD</div>
  </div>
);

export default CurrencySelector;
