/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NavItemProps {
  text: string;
  hasDropdown?: boolean;
}

const NavItem: React.FC<NavItemProps> = ({ text, hasDropdown = false }) => (
  <div className="flex justify-center items-start">
    <div className="flex gap-2.5 items-center px-4 py-px">
      <div className="self-stretch my-auto text-sm font-medium text-center text-white uppercase leading-[60px] tracking-[2.1px]">
        {text}
      </div>
      {hasDropdown && (
        <div className="flex items-start self-stretch my-auto w-[11px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2226e0516cde8ae28d411d728b7c7b09011a3b338036aed7a572cf787a3aa218?placeholderIfAbsent=true&apiKey=ae55c71ab31c4b56a85baaeb8b56efa9"
            className="object-contain aspect-[0.79] w-[11px]"
            alt=""
          />
        </div>
      )}
    </div>
  </div>
);

export default NavItem;
