/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface IconButtonProps {
  src: string;
  alt: string;
  width: string;
  aspectRatio: string;
}

const IconButton: React.FC<IconButtonProps> = ({
  src,
  alt,
  width,
  aspectRatio,
}) => (
  <div className="flex flex-col items-end self-stretch pb-1.5 pl-2.5 my-auto">
    <div className={`flex items-start pb-px w-full max-w-[${width}]`}>
      <div className={`flex items-start w-[${width}]`}>
        <div className={`flex items-start w-[${width}]`}>
          <img
            loading="lazy"
            src={src}
            className={`object-contain aspect-[${aspectRatio}] w-[${width}]`}
            alt={alt}
          />
        </div>
      </div>
    </div>
  </div>
);

export default IconButton;
