/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => (
  <div className="flex flex-col grow shrink self-stretch px-1 my-auto min-w-[240px] w-[300px]">
    <div className="flex flex-col max-w-full w-[367px]">
      <div className="flex flex-col justify-center items-center px-16 w-full max-md:px-5">
        <div className="flex justify-center items-start pb-1 max-w-full w-[230px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a71205256218f1bd4173e1daadc183adae0e3e50d190112162f1a0e701357090?placeholderIfAbsent=true&apiKey=ae55c71ab31c4b56a85baaeb8b56efa9"
            className="object-contain aspect-[9.17] max-w-[230px] w-[230px]"
            alt="Company logo"
          />
        </div>
      </div>
    </div>
  </div>
);

export default Logo;
