/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TopBanner: React.FC = () => (
  <header className="flex flex-col w-full text-xs tracking-wider leading-10 text-center text-black uppercase bg-red-100 max-md:max-w-full">
    <div className="flex flex-col items-center pr-5 w-full max-md:max-w-full">
      <div className="flex flex-col items-center w-full max-w-[1901px] max-md:max-w-full">
        <p>Free Shipping on U.S. & Canada Orders</p>
      </div>
    </div>
  </header>
);

export default TopBanner;
